#!/usr/bin/env python3
"""Auto-register local celestia-island npm packages as local-path overrides.

pnpm (recommended) — writes ``pnpm.overrides`` in ``pnpm-workspace.yaml``
so that ``@celestia-island/*`` dependencies are resolved from sibling repos
instead of the npm registry. npm and yarn users receive a warning — the
celestia-island build tooling is designed around pnpm.

The scan directory for sibling repos is resolved in this order:

1. ``--scan-dir`` CLI argument (explicit)
2. ``CELESTIA_ROOT`` environment variable
3. The parent directory of the current working directory (fallback)

Usage::

    celestia-devtools register-npm-patches
    celestia-devtools register-npm-patches --scan-dir /path/to/celestia
    celestia-devtools register-npm-patches --dry-run
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path
from typing import NamedTuple


class NpmPackage(NamedTuple):
    """An npm package discovered inside a sibling repo."""

    name: str       # full package name (e.g. "@celestia-island/hikari")
    path: Path      # absolute path to the directory containing package.json
    repo: str       # repo name (e.g. "hikari")
    version: str    # declared version (e.g. "0.4.0")


# ── discovery ──────────────────────────────────────────────────────────────


def _git_remote_origin(repo_path: Path) -> str | None:
    """Return the origin URL for *repo_path*, or ``None``."""
    try:
        import subprocess as _subprocess

        r = _subprocess.run(
            ["git", "-C", str(repo_path), "remote", "get-url", "origin"],
            capture_output=True, text=True, timeout=10,
        )
        if r.returncode == 0:
            return r.stdout.strip()
    except (OSError, _subprocess.SubprocessError):
        pass
    return None


def is_celestia_repo(repo_path: Path) -> str | None:
    """Check if *repo_path* is a celestia-island git repo."""
    url = _git_remote_origin(repo_path)
    if not url:
        return None
    m = re.search(r"celestia-island[:/]([^/]+?)(?:\.git)?$", url)
    return m.group(1) if m else None


def discover_npm_packages(repo_path: Path, repo_name: str) -> list[NpmPackage]:
    """Find all ``@celestia-island/*`` npm packages inside *repo_path*.

    Searches recursively for ``package.json`` files (limited to 4 levels deep
    from repo root for performance).
    """
    packages: list[NpmPackage] = []
    try:
        for pkg_json in sorted(repo_path.glob("packages/*/package.json")):
            if not pkg_json.is_file():
                continue
            try:
                data = json.loads(pkg_json.read_text(encoding="utf-8", errors="ignore"))
            except json.JSONDecodeError:
                continue
            name = data.get("name")
            version = data.get("version", "0.0.0")
            if isinstance(name, str) and name.startswith("@celestia-island/"):
                packages.append(NpmPackage(
                    name=name,
                    path=pkg_json.parent.resolve(),
                    repo=repo_name,
                    version=version,
                ))
    except OSError:
        pass
    return packages


def scan_celestia_npm_packages(scan_dir: Path, *, exclude_repo: str | None = None) -> list[NpmPackage]:
    """Scan *scan_dir* for celestia-island sibling repos with npm packages.

    If *exclude_repo* is provided, packages whose repo name matches are skipped
    (prevents self-references when scanning from within the target repo).
    """
    packages: list[NpmPackage] = []
    if not scan_dir.is_dir():
        return packages

    for entry in sorted(scan_dir.iterdir()):
        if not entry.is_dir() or entry.name.startswith("."):
            continue
        if not (entry / ".git").exists():
            continue
        repo_name = is_celestia_repo(entry)
        if not repo_name:
            continue
        if exclude_repo and repo_name == exclude_repo:
            continue
        found = discover_npm_packages(entry, repo_name)
        packages.extend(found)

    return packages


# ── pnpm workspace overrides ───────────────────────────────────────────────

START_MARKER = "# ── celestia-devtools auto-registered npm overrides ──"
END_MARKER = "# ── end celestia-devtools npm overrides ──"


def _build_overrides_block(packages: list[NpmPackage], target_dir: Path) -> str:
    """Generate a ``pnpm.overrides`` block mapping sibling packages."""
    lines = [START_MARKER]
    lines.append("# Generated by `celestia-devtools register-npm-patches`.")
    lines.append("# pnpm will resolve these from local checkouts instead of the npm registry.")
    lines.append("")
    lines.append("pnpm:")
    lines.append("  overrides:")

    for pkg in sorted(packages, key=lambda p: p.name):
        rel = os.path.relpath(str(pkg.path), str(target_dir))
        if not rel.startswith("."):
            rel = f"./{rel}"
        lines.append(f'    "{pkg.name}": "link:{rel}"')

    lines.append("")
    lines.append(END_MARKER)
    return "\n".join(lines) + "\n"


def _replace_or_append_overrides(
    text: str, new_block: str,
) -> str:
    """Replace an existing devtools overrides block, or append a new one."""
    if START_MARKER in text:
        parts = re.split(
            re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER),
            text, flags=re.S,
        )
        if len(parts) >= 2:
            return parts[0].rstrip() + "\n\n" + new_block + parts[1].lstrip()
    return text.rstrip() + "\n\n" + new_block


def detect_package_manager(target_dir: Path) -> str:
    """Detect which package manager is in use.

    Returns one of: ``"pnpm"``, ``"npm"``, ``"yarn"``, ``"unknown"``.
    """
    files = sorted(os.listdir(target_dir)) if target_dir.is_dir() else []

    # pnpm
    if "pnpm-lock.yaml" in files or "pnpm-workspace.yaml" in files:
        return "pnpm"

    # yarn
    if "yarn.lock" in files:
        return "yarn"

    # npm
    if "package-lock.json" in files:
        return "npm"

    return "unknown"


def _print_npm_warning(packages: list[NpmPackage], target_dir: Path) -> None:
    """Print a warning for npm/yarn users with manual override instructions."""
    print("\033[33m" + "=" * 60 + "\033[0m", file=sys.stderr)
    print("\033[33m WARNING: npm/yarn detected.\033[0m", file=sys.stderr)
    print(
        "\033[33m celestia-island build tooling requires pnpm. "
        "Please install pnpm and run:\033[0m",
        file=sys.stderr,
    )
    print("\033[33m   npm install -g pnpm\033[0m", file=sys.stderr)
    print("\033[33m   rm -rf node_modules package-lock.json yarn.lock\033[0m", file=sys.stderr)
    print("\033[33m   pnpm install\033[0m", file=sys.stderr)
    print("\033[33m" + "=" * 60 + "\033[0m", file=sys.stderr)

    print("", file=sys.stderr)
    print(
        "If you insist on continuing without pnpm, add the following to your "
        "package.json:",
        file=sys.stderr,
    )
    print("", file=sys.stderr)

    for pkg in sorted(packages, key=lambda p: p.name):
        rel = os.path.relpath(str(pkg.path), str(target_dir))
        if not rel.startswith("."):
            rel = f"./{rel}"
        print(f'  "{pkg.name}": "file:{rel}",', file=sys.stderr)

    print("", file=sys.stderr)


def update_pnpm_workspace(
    new_block: str,
    workspace_path: Path,
    *,
    dry_run: bool = False,
) -> bool:
    """Insert/update the overrides block in a pnpm-workspace.yaml file."""
    existing = ""
    if workspace_path.is_file():
        existing = workspace_path.read_text(encoding="utf-8", errors="ignore")

    new_text = _replace_or_append_overrides(existing, new_block)

    if new_text.rstrip() == existing.rstrip():
        return False

    if dry_run:
        print(f"[register-npm-patches] dry-run: would update {workspace_path}")
        print("--- new block ---")
        print(new_block)
        return True

    workspace_path.write_text(new_text, encoding="utf-8")
    print(f"[register-npm-patches] updated {workspace_path}")
    return True


# ── scan directory resolution ─────────────────────────────────────────────


def _resolve_scan_dir(explicit: str | None) -> Path:
    if explicit:
        return Path(explicit)
    env_root = os.environ.get("CELESTIA_ROOT")
    if env_root:
        return Path(env_root)
    return Path.cwd().parent


# ── CLI ───────────────────────────────────────────────────────────────────


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Auto-register @celestia-island npm packages as local overrides",
    )
    parser.add_argument(
        "--scan-dir", default=None,
        help="directory to scan for sibling repos "
             "(env: CELESTIA_ROOT; default: parent of cwd)",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="show what would change without writing",
    )
    args = parser.parse_args()

    scan_dir = _resolve_scan_dir(args.scan_dir)
    target_dir = Path.cwd().resolve()
    own_repo = is_celestia_repo(target_dir)

    print(f"[register-npm-patches] scanning {scan_dir} …")
    packages = scan_celestia_npm_packages(scan_dir, exclude_repo=own_repo)

    if not packages:
        print(
            "[register-npm-patches] no @celestia-island npm packages found in sibling repos",
            file=sys.stderr,
        )
        return 1

    print(
        f"[register-npm-patches] found {len(packages)} npm package(s) in sibling repos:",
    )
    for pkg in packages:
        rel = os.path.relpath(str(pkg.path), str(target_dir))
        print(f"  {pkg.name}@{pkg.version} -> {rel}")

    pm = detect_package_manager(target_dir)
    print(f"[register-npm-patches] detected package manager: {pm}")

    if pm != "pnpm":
        _print_npm_warning(packages, target_dir)
        return 1

    # pnpm path
    workspace_path = target_dir / "pnpm-workspace.yaml"
    if not workspace_path.is_file():
        print(
            "[register-npm-patches] pnpm-workspace.yaml not found. "
            "Are you in the right directory?",
            file=sys.stderr,
        )
        return 1

    new_block = _build_overrides_block(packages, target_dir)
    changed = update_pnpm_workspace(
        new_block, workspace_path, dry_run=args.dry_run,
    )

    if changed:
        print("[register-npm-patches] done — run `pnpm install` to apply")
    else:
        print("[register-npm-patches] already up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
