#!/usr/bin/env python3
"""The deploy profile: the single configuration face for one target instance.

One face == one systemd unit == one config file at ``/etc/celestia/<face>.env``
plus a ``<face>.profile.toml`` next to it. The profile is the *only* thing the
wizard writes, the only thing bootstrap reads, and it never contains secrets —
secrets live in the 0600 env file generated by the secrets stage.

TOML round-trip goes through tomli-w/tomllib (no hand-rolled emitter, per the
plan's settled policy). Sections mirror the plan's profile.toml sketch.
"""

from __future__ import annotations

import os
import re
from dataclasses import dataclass, field, fields, asdict
from pathlib import Path
from typing import Any

import tomli_w

try:  # Python >= 3.11 (our floor)
    import tomllib
except ImportError:  # pragma: no cover
    tomllib = None  # type: ignore[assignment]

FACE_RE = re.compile(r"^[a-z][a-z0-9-]{0,30}$")
EMAIL_RE = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")
LEVELS = ("hosted", "selfhosted")
FACE_COMMENT = "# generated by celestia-devtools deploy; NOT a secret store"


_PLAIN_TYPES = {"int": int, "str": str, "bool": bool}


def _field_type(annotation) -> type | None:
    """Runtime type for the plain str/int/bool fields we ship.

    With `from __future__ import annotations` (this module uses it) field
    types arrive as STRINGS ("int"), so resolve the literal; anything else
    (Optional[…], nested) is skipped — wrong-type rejection only covers the
    fields whose wrong type silently flips semantics."""
    if isinstance(annotation, str):
        return _PLAIN_TYPES.get(annotation)
    import typing
    if typing.get_origin(annotation) is not None:
        return None
    return annotation if isinstance(annotation, type) else None


class ProfileError(ValueError):
    """Validation failure with a field path for actionable messages."""


@dataclass
class HostSection:
    face: str = "chest"
    admin_user: str = "celestia"
    level: str = "hosted"  # hosted (our machine) | selfhosted (customer-held)
    listen: int = 3000  # app port; the front binds 443. Never 80 (nginx clash)
    # Bases are configurable so tests (and exotic layouts) never need /srv or
    # /etc; defaults match the house layout.
    srv_base: str = "/srv/celestia"
    etc_base: str = "/etc/celestia"

    def deploy_root(self) -> Path:
        return Path(self.srv_base) / self.face

    def etc_env(self) -> Path:
        return Path(self.etc_base) / "{}.env".format(self.face)

    def profile_path(self) -> Path:
        return Path(self.etc_base) / "{}.profile.toml".format(self.face)

    def unit_name(self) -> str:
        return "{}.service".format(self.face)


@dataclass
class ArtifactSection:
    # file:// or https:// index for D3; a bare file path works for tests.
    source: str = "file:///opt/celestia-devtools/artifacts/index.toml"
    channel: str = "stable"


@dataclass
class DatabaseSection:
    mode: str = "external"  # external | local
    url_file: str = ""      # empty = D3 derives from host.etc_base; never inline URLs


@dataclass
class FrontSection:
    enabled: bool = True
    domain: str = ""        # required when enabled (HTTP-01 only, no int-DNS)
    email: str = ""         # ACME account contact


@dataclass
class AdminSection:
    email: str = ""         # first registered user; auto-promoted, no captcha
    password_to_file: bool = False  # False: print once on stdout


@dataclass
class DeployProfile:
    host: HostSection = field(default_factory=HostSection)
    artifact: ArtifactSection = field(default_factory=ArtifactSection)
    database: DatabaseSection = field(default_factory=DatabaseSection)
    front: FrontSection = field(default_factory=FrontSection)
    admin: AdminSection = field(default_factory=AdminSection)

    # ── validation ────────────────────────────────────────────────────

    def validate(self) -> list[str]:
        errors: list[str] = []
        if not FACE_RE.match(self.host.face):
            errors.append("host.face: lowercase slug required, got {!r}".format(self.host.face))
        if not (1 <= int(self.host.listen) <= 65535):
            errors.append("host.listen: port out of range: {}".format(self.host.listen))
        if self.host.level not in LEVELS:
            errors.append("host.level: one of {} required".format(LEVELS))
        if self.front.enabled:
            if not self.front.domain:
                errors.append("front.domain: required when front.enabled")
            if self.front.email and not EMAIL_RE.match(self.front.email):
                errors.append("front.email: invalid address {!r}".format(self.front.email))
        if self.admin.email and not EMAIL_RE.match(self.admin.email):
            errors.append("admin.email: invalid address {!r}".format(self.admin.email))
        if self.database.mode not in ("external", "local"):
            errors.append("database.mode: external|local required")
        return errors

    # ── TOML round-trip ───────────────────────────────────────────────

    def to_dict(self) -> dict[str, Any]:
        return {sec.name: asdict(getattr(self, sec.name))
                for sec in fields(self)}

    def to_toml(self) -> str:
        doc = self.to_dict()
        text = tomli_w.dumps(doc)
        return FACE_COMMENT + "\n" + text

    @classmethod
    def from_toml(cls, text: str) -> "DeployProfile":
        if tomllib is None:  # pragma: no cover
            raise ProfileError("tomllib unavailable (below 3.11)")
        doc = tomllib.loads(text)
        profile = cls()
        known = {f.name for f in fields(profile)}
        unknown_top = set(doc) - known
        if unknown_top:
            raise ProfileError(
                "unknown top-level section(s): {} (typo?)".format(
                    ", ".join(sorted(unknown_top))))
        for sec in fields(profile):
            incoming = doc.get(sec.name)
            if incoming is None:
                continue
            section = getattr(profile, sec.name)
            known = {f.name for f in fields(section)}
            types = {f.name: _field_type(f.type) for f in fields(section)}
            for key, value in incoming.items():
                if key not in known:
                    raise ProfileError("{}.{}: unknown key".format(sec.name, key))
                want = types.get(key)
                if want is not None and (value is None or not isinstance(value, want)):
                    raise ProfileError(
                        "{}.{}: expected {}, got {!r}".format(
                            sec.name, key, getattr(want, "__name__", want), value))
                setattr(section, key, value)
        errors = profile.validate()
        if errors:
            raise ProfileError("; ".join(errors))
        return profile

    def write(self, path: Path) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(self.to_toml(), encoding="utf-8")
        os.chmod(path, 0o600)  # reveals topology even without secrets

    @classmethod
    def read(cls, path: Path) -> "DeployProfile":
        return cls.from_toml(path.read_text(encoding="utf-8"))
